### ISSUE TITLE
UX breaking for mobile devices

### ISSUE THREAD

**Issue by Ritesh-Dabral** [praveen8git/Link-Shrink#1]
The search bar goes out of window when opened on mobile screen 

<img width="468" alt="Screenshot 2023-10-01 at 2 44 26 PM" src="https://github.com/praveen8git/Link-Shrink/assets/36252036/a3137f55-e82b-442d-b87c-7fc8505ce608">

**Comment by Ritesh-Dabral** [comment]
@praveen8git Please assign this issue to me

**Comment by Sahilm416** [comment]
hey @praveen8git  i would like to work on this issue ! 
also can you please add "hactoberfest" and "hactoberfest-accepted" tags , it will really help !

**Comment by praveen8git** [comment]
sure, done!

**Comment by Sahilm416** [comment]
@praveen8git i guess the tags aren't added there...
