### ISSUE TITLE
Url is not shrinking 

### ISSUE THREAD

**Issue by AyusGup** [praveen8git/Link-Shrink#6]
![image](https://github.com/praveen8git/Link-Shrink/assets/127961367/c3f59059-62fe-4d8a-b9c7-cad262d35b51)

url tried : https://drive.google.com/file/d/1T5iKoVenLhcUohKg_MvnNrns3v4gFK6m/view?pli=1

**Comment by AyusGup** [comment]
please assign this issue to me

**Comment by praveen8git** [comment]
@AyusGup Hi! It was due to a problem with hosting. Please clone this project in your localhost then try again.

**Comment by Sahilm416** [comment]
yes it works fine locally !

**Comment by AyusGup** [comment]
hmm i have seen its working
